/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KUMAR SHIVAM
 */
import java.awt.Color;
public class Backgroundchange extends javax.swing.JFrame {

    /**
     * Creates new form Backgroundchange
     */
    public Backgroundchange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colorLst = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        Lbl = new javax.swing.JLabel();
        Btn = new javax.swing.JButton();
        TF = new javax.swing.JTextField();
        lblChk = new javax.swing.JCheckBox();
        btnChk = new javax.swing.JCheckBox();
        tfChk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Select Color");

        colorLst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Red", "Blue", "Green", "Magentia", "Cyan", "Yellow", "Gray" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        colorLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                colorLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(colorLst);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Affected Control");

        Lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lbl.setText("I am Label");
        Lbl.setOpaque(true);

        Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn.setText("I am Button");
        Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActionPerformed(evt);
            }
        });

        TF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TF.setText("jTextField1");
        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });

        lblChk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChk.setText("Apply on label");
        lblChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblChkActionPerformed(evt);
            }
        });

        btnChk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChk.setText("Apply on button");
        btnChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChkActionPerformed(evt);
            }
        });

        tfChk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfChk.setText("Apply on textfield");
        tfChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChk)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl))
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btn)
                                .addGap(136, 136, 136))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnChk)
                        .addGap(54, 54, 54)
                        .addComponent(tfChk)
                        .addGap(0, 108, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChk)
                    .addComponent(btnChk)
                    .addComponent(tfChk))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFActionPerformed

    private void btnChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChkActionPerformed
        // TODO add your handling code here:
        int i;
        Color x =Color.WHITE;
        i = colorLst.getSelectedIndex();
        switch(i){
            case 0 : x = Color.RED;
                break;
            case 1 : x = Color.BLUE;
                break;
            case 2 : x = Color.GREEN;
                break;
            case 3 : x = Color.MAGENTA;
                break;
            case 4 : x = Color.CYAN;
                break;
            case 5 : x = Color.YELLOW;
                break;
            case 6 : x = Color.GRAY;
                break;
        }
        if(lblChk.isSelected())
            Lbl.setBackground(x);
        else
            Lbl.setBackground(Color.WHITE);
        if(btnChk.isSelected())
            Btn.setBackground(x);
        else
            Btn.setBackground(Color.WHITE);
        if(tfChk.isSelected())
            TF.setBackground(x);
        else
            TF.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnChkActionPerformed

    private void colorLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_colorLstValueChanged
        // TODO add your handling code here:
        int i;
        Color x =Color.WHITE;
        i = colorLst.getSelectedIndex();
        switch(i){
            case 0 : x = Color.RED;
                break;
            case 1 : x = Color.BLUE;
                break;
            case 2 : x = Color.GREEN;
                break;
            case 3 : x = Color.MAGENTA;
                break;
            case 4 : x = Color.CYAN;
                break;
            case 5 : x = Color.YELLOW;
                break;
            case 6 : x = Color.GRAY;
                break;
        }
        if(lblChk.isSelected())
            Lbl.setBackground(x);
        else
            Lbl.setBackground(Color.WHITE);
        if(btnChk.isSelected())
            Btn.setBackground(x);
        else
            Btn.setBackground(Color.WHITE);
        if(tfChk.isSelected())
            TF.setBackground(x);
        else
            TF.setBackground(Color.WHITE);
    }//GEN-LAST:event_colorLstValueChanged

    private void lblChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblChkActionPerformed
        // TODO add your handling code here:
        int i;
        Color x =Color.WHITE;
        i = colorLst.getSelectedIndex();
        switch(i){
            case 0 : x = Color.RED;
                break;
            case 1 : x = Color.BLUE;
                break;
            case 2 : x = Color.GREEN;
                break;
            case 3 : x = Color.MAGENTA;
                break;
            case 4 : x = Color.CYAN;
                break;
            case 5 : x = Color.YELLOW;
                break;
            case 6 : x = Color.GRAY;
                break;
        }
        if(lblChk.isSelected())
            Lbl.setBackground(x);
        else
            Lbl.setBackground(Color.WHITE);
        if(btnChk.isSelected())
            Btn.setBackground(x);
        else
            Btn.setBackground(Color.WHITE);
        if(tfChk.isSelected())
            TF.setBackground(x);
        else
            TF.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_lblChkActionPerformed

    private void tfChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChkActionPerformed
        // TODO add your handling code here:
        int i;
        Color x =Color.WHITE;
        i = colorLst.getSelectedIndex();
        switch(i){
            case 0 : x = Color.RED;
                break;
            case 1 : x = Color.BLUE;
                break;
            case 2 : x = Color.GREEN;
                break;
            case 3 : x = Color.MAGENTA;
                break;
            case 4 : x = Color.CYAN;
                break;
            case 5 : x = Color.YELLOW;
                break;
            case 6 : x = Color.GRAY;
                break;
        }
        if(lblChk.isSelected())
            Lbl.setBackground(x);
        else
            Lbl.setBackground(Color.WHITE);
        if(btnChk.isSelected())
            Btn.setBackground(x);
        else
            Btn.setBackground(Color.WHITE);
        if(tfChk.isSelected())
            TF.setBackground(x);
        else
            TF.setBackground(Color.WHITE);
    }//GEN-LAST:event_tfChkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Backgroundchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Backgroundchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Backgroundchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Backgroundchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Backgroundchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn;
    private javax.swing.JLabel Lbl;
    private javax.swing.JTextField TF;
    private javax.swing.JCheckBox btnChk;
    private javax.swing.JList colorLst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox lblChk;
    private javax.swing.JCheckBox tfChk;
    // End of variables declaration//GEN-END:variables
}
